name: 'App CI Merge bot'
description: 'Automatic merges for a Gitflow workflow'
inputs:
  slack-url:  
    description: 'The slack workflow URL to notify a channel'
    required: true
  slack-channel:  
    description: 'The channel to notify'
    required: false
outputs:
  time: # id of output
    description: 'Merge complete'
runs:
  using: 'ubuntu-latest'
  main: 'merge_report.pl'